---
- name: Create SSH directory if not existing
  ansible.builtin.file:
    path: /home/vagrant/.ssh
    state: directory
    owner: vagrant
    group: vagrant
    mode: '0700'

- name: Download Vagrant's insecure SSH key
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/hashicorp/vagrant/refs/heads/master/keys/vagrant.pub
    dest: /home/vagrant/.ssh/authorized_keys
    owner: vagrant
    group: vagrant
    mode: 'O600'
